// <auto-generated />
namespace ZHYR_Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_reD_nd_downloD_TOO_BOOK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_reD_nd_downloD_TOO_BOOK));
        
        string IMigrationMetadata.Id
        {
            get { return "201709251522416_Add_reD_nd_downloD_TOO-_BOOK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
