//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHYR_Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZHYR_Library.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book Ekle.
        /// </summary>
        public static string add_book {
            get {
                return ResourceManager.GetString("add_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin İşleri.
        /// </summary>
        public static string adminişleri {
            get {
                return ResourceManager.GetString("adminişleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Manage.
        /// </summary>
        public static string AdminManage {
            get {
                return ResourceManager.GetString("AdminManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Profile.
        /// </summary>
        public static string AdminProfile {
            get {
                return ResourceManager.GetString("AdminProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabça.
        /// </summary>
        public static string Ar {
            get {
                return ResourceManager.GetString("Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arapça.
        /// </summary>
        public static string arabic {
            get {
                return ResourceManager.GetString("arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to author Adi.
        /// </summary>
        public static string author_name {
            get {
                return ResourceManager.GetString("author_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book Adi.
        /// </summary>
        public static string book_name {
            get {
                return ResourceManager.GetString("book_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitap ilgili.
        /// </summary>
        public static string bookAbout {
            get {
                return ResourceManager.GetString("bookAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book Açıklama.
        /// </summary>
        public static string bookAcıklama {
            get {
                return ResourceManager.GetString("bookAcıklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book Arayin.
        /// </summary>
        public static string bookarayin {
            get {
                return ResourceManager.GetString("bookarayin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitap Ayrıntısı.
        /// </summary>
        public static string bookDetails {
            get {
                return ResourceManager.GetString("bookDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book Detayli.
        /// </summary>
        public static string bookDetayli {
            get {
                return ResourceManager.GetString("bookDetayli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book fotoğrafi.
        /// </summary>
        public static string bookImage {
            get {
                return ResourceManager.GetString("bookImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to books.
        /// </summary>
        public static string books {
            get {
                return ResourceManager.GetString("books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitap ara.
        /// </summary>
        public static string bookSearch {
            get {
                return ResourceManager.GetString("bookSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölümler.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bölüm Adi.
        /// </summary>
        public static string category_name {
            get {
                return ResourceManager.GetString("category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bölüm fotoğrafi.
        /// </summary>
        public static string categoryImage {
            get {
                return ResourceManager.GetString("categoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifre değişter.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string çikiş {
            get {
                return ResourceManager.GetString("çikiş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok İndirilen.
        /// </summary>
        public static string cokindirilen {
            get {
                return ResourceManager.GetString("cokindirilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok Okunan.
        /// </summary>
        public static string cokOkunan {
            get {
                return ResourceManager.GetString("cokOkunan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değer books.
        /// </summary>
        public static string Degerbooks {
            get {
                return ResourceManager.GetString("Degerbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detayli.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam.
        /// </summary>
        public static string devam {
            get {
                return ResourceManager.GetString("devam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Dil {
            get {
                return ResourceManager.GetString("Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indir.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book Düzenle .
        /// </summary>
        public static string Edit_book {
            get {
                return ResourceManager.GetString("Edit_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingilizce.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingilizce.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adi.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to galeri.
        /// </summary>
        public static string galeri {
            get {
                return ResourceManager.GetString("galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to galeri.
        /// </summary>
        public static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayrullah kitaplari.
        /// </summary>
        public static string H4Books {
            get {
                return ResourceManager.GetString("H4Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayrullah.
        /// </summary>
        public static string Hayrullah {
            get {
                return ResourceManager.GetString("Hayrullah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnaSayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iletişim.
        /// </summary>
        public static string iletişim {
            get {
                return ResourceManager.GetString("iletişim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraflar.
        /// </summary>
        public static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to işleri.
        /// </summary>
        public static string işleri {
            get {
                return ResourceManager.GetString("işleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string Kategori {
            get {
                return ResourceManager.GetString("Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorler.
        /// </summary>
        public static string Kategorler {
            get {
                return ResourceManager.GetString("Kategorler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanci.
        /// </summary>
        public static string Kullanci {
            get {
                return ResourceManager.GetString("Kullanci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanci Adi.
        /// </summary>
        public static string KullanciAdi {
            get {
                return ResourceManager.GetString("KullanciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadi.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok İndiren.
        /// </summary>
        public static string MostDownlods {
            get {
                return ResourceManager.GetString("MostDownlods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çok Okunan.
        /// </summary>
        public static string MostRead {
            get {
                return ResourceManager.GetString("MostRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mybooks.
        /// </summary>
        public static string mybooks {
            get {
                return ResourceManager.GetString("mybooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kitaplar.
        /// </summary>
        public static string NewBooks {
            get {
                return ResourceManager.GetString("NewBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string pages {
            get {
                return ResourceManager.GetString("pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanci özellikleri.
        /// </summary>
        public static string personel {
            get {
                return ResourceManager.GetString("personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numurası.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilim.
        /// </summary>
        public static string Profilim {
            get {
                return ResourceManager.GetString("Profilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okuma.
        /// </summary>
        public static string read {
            get {
                return ResourceManager.GetString("read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifre.
        /// </summary>
        public static string şifre {
            get {
                return ResourceManager.GetString("şifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to şifre Değiştir.
        /// </summary>
        public static string şifreDeğiştir {
            get {
                return ResourceManager.GetString("şifreDeğiştir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oturma aç.
        /// </summary>
        public static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oturma kapat.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şiirler.
        /// </summary>
        public static string şiirler {
            get {
                return ResourceManager.GetString("şiirler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Tr {
            get {
                return ResourceManager.GetString("Tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkçe.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvirsite.
        /// </summary>
        public static string universite {
            get {
                return ResourceManager.GetString("universite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to üniversiteler.
        /// </summary>
        public static string universities {
            get {
                return ResourceManager.GetString("universities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kullanci.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uye Giriş.
        /// </summary>
        public static string UyeGiriş {
            get {
                return ResourceManager.GetString("UyeGiriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uye Ol.
        /// </summary>
        public static string uyeol {
            get {
                return ResourceManager.GetString("uyeol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writers.
        /// </summary>
        public static string writers {
            get {
                return ResourceManager.GetString("writers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni books.
        /// </summary>
        public static string yenibooks {
            get {
                return ResourceManager.GetString("yenibooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yonetici Adi.
        /// </summary>
        public static string yoneticiAdi {
            get {
                return ResourceManager.GetString("yoneticiAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yonetici Profili.
        /// </summary>
        public static string Yoneticiprofil {
            get {
                return ResourceManager.GetString("Yoneticiprofil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zekitaplari.
        /// </summary>
        public static string Zekitaplari {
            get {
                return ResourceManager.GetString("Zekitaplari", resourceCulture);
            }
        }
    }
}
