//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHYR_Library.Models.EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZHYR_EF_DB : DbContext
    {
        public ZHYR_EF_DB()
            : base("name=ZHYR_EF_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TopDownloaded10> TopDownloaded10 { get; set; }
        public virtual DbSet<TopDownloaded100> TopDownloaded100 { get; set; }
        public virtual DbSet<TopLiked10> TopLiked10 { get; set; }
        public virtual DbSet<TopLiked100> TopLiked100 { get; set; }
        public virtual DbSet<TopReaded10> TopReaded10 { get; set; }
        public virtual DbSet<TopReaded100> TopReaded100 { get; set; }
        public virtual DbSet<TopPosts10> TopPosts10 { get; set; }
        public virtual DbSet<TopPosts100> TopPosts100 { get; set; }
    }
}
