//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHYR_Library.Models.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopDownloaded100
    {
        public int id { get; set; }
        public string book_name { get; set; }
        public string book_about { get; set; }
        public string image { get; set; }
        public string book_path { get; set; }
        public System.DateTime Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
        public int UserId { get; set; }
        public int author_id { get; set; }
        public int category_id { get; set; }
        public int favorited { get; set; }
        public int downloaded { get; set; }
        public int Readed { get; set; }
        public int disLike { get; set; }
        public int Liked { get; set; }
    }
}
