//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZHYR_Library.Models.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopPosts100
    {
        public int Id { get; set; }
        public string image { get; set; }
        public string Title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public System.DateTime Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<System.DateTime> Deleted_at { get; set; }
        public int UserId { get; set; }
        public int category_id { get; set; }
    }
}
